<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Create tables for resource farming system
 */
final class Version20250728203500 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create resource_locations, user_gathering_level and resource_gathering_history tables';
    }

    public function up(Schema $schema): void
    {
        // Создание таблицы resource_locations
        $this->addSql('CREATE TABLE resource_locations (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, 
            name VARCHAR(100) NOT NULL, 
            description TEXT DEFAULT NULL, 
            category VARCHAR(50) NOT NULL, 
            tier INT NOT NULL, 
            drop_chance NUMERIC(5, 2) NOT NULL, 
            min_amount INT DEFAULT 1 NOT NULL, 
            max_amount INT DEFAULT 1 NOT NULL, 
            location_id INT NOT NULL, 
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE INDEX IDX_BF2F192564D218E ON resource_locations (location_id)');
        
        // Создание таблицы user_gathering_level
        $this->addSql('CREATE TABLE user_gathering_level (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, 
            alchemy_lvl INT DEFAULT 0 NOT NULL, 
            hunting_lvl INT DEFAULT 0 NOT NULL, 
            mines_lvl INT DEFAULT 0 NOT NULL, 
            fishing_lvl INT DEFAULT 0 NOT NULL, 
            farm_lvl INT DEFAULT 0 NOT NULL, 
            alchemy_exp INT DEFAULT 0 NOT NULL, 
            hunting_exp INT DEFAULT 0 NOT NULL, 
            mines_exp INT DEFAULT 0 NOT NULL, 
            fishing_exp INT DEFAULT 0 NOT NULL, 
            farm_exp INT DEFAULT 0 NOT NULL, 
            user_id INT NOT NULL, 
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE INDEX IDX_506E5EC4A76ED395 ON user_gathering_level (user_id)');
        
        // Создание таблицы resource_gathering_history
        $this->addSql('CREATE TABLE resource_gathering_history (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, 
            data JSON NOT NULL, 
            timestamp TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, 
            user_id INT NOT NULL, 
            location_id INT NOT NULL, 
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE INDEX IDX_9DF06E08A76ED395 ON resource_gathering_history (user_id)');
        $this->addSql('CREATE INDEX IDX_9DF06E0864D218E ON resource_gathering_history (location_id)');
        
        // Добавление внешних ключей
        $this->addSql('ALTER TABLE resource_locations ADD CONSTRAINT FK_BF2F192564D218E FOREIGN KEY (location_id) REFERENCES locations (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE resource_gathering_history ADD CONSTRAINT FK_9DF06E08A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE resource_gathering_history ADD CONSTRAINT FK_9DF06E0864D218E FOREIGN KEY (location_id) REFERENCES locations (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_gathering_level ADD CONSTRAINT FK_506E5EC4A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // Удаление внешних ключей и таблиц в правильном порядке
        $this->addSql('ALTER TABLE resource_gathering_history DROP CONSTRAINT FK_9DF06E08A76ED395');
        $this->addSql('ALTER TABLE resource_gathering_history DROP CONSTRAINT FK_9DF06E0864D218E');
        $this->addSql('ALTER TABLE resource_locations DROP CONSTRAINT FK_BF2F192564D218E');
        $this->addSql('ALTER TABLE user_gathering_level DROP CONSTRAINT FK_506E5EC4A76ED395');
        
        $this->addSql('DROP TABLE resource_gathering_history');
        $this->addSql('DROP TABLE resource_locations');
        $this->addSql('DROP TABLE user_gathering_level');
    }
}
