<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Миграция для создания таблицы gathering_levels
 */
final class Version20250728185100 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Создание таблицы уровней добычи ресурсов';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE gathering_levels (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, 
            level INT NOT NULL, 
            total_experience BIGINT NOT NULL, 
            PRIMARY KEY (id)
        )');
        
        // Заполняем таблицу уровней на основе формулы опыта
        $baseExp = 2;
        $power = 1.8;
        $totalExp = 0;
        
        for ($level = 1; $level <= 150; $level++) {
            $expForLevel = (int) ceil($baseExp * pow($level, $power));
            $totalExp += $expForLevel;
            
            $this->addSql('INSERT INTO gathering_levels (level, total_experience) VALUES (:level, :totalExp)', [
                'level' => $level,
                'totalExp' => $totalExp
            ]);
        }
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE gathering_levels');
    }
}
