<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Миграция для удаления старой таблицы resources и создания новой по структуре сущности Resource
 */
final class Version20250728225400 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Удаление старой таблицы resources и создание новой по структуре сущности Resource';
    }

    public function up(Schema $schema): void
    {
        // Сначала удаляем старую таблицу, если она существует
        $this->addSql('DROP TABLE IF EXISTS resources');
        
        // Создаем новую таблицу с нужной структурой
        $this->addSql('CREATE TABLE resources (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            name VARCHAR(100) NOT NULL,
            description TEXT DEFAULT NULL,
            category VARCHAR(50) NOT NULL,
            rarity VARCHAR(20) NOT NULL,
            drop_chance DOUBLE PRECISION NOT NULL,
            PRIMARY KEY(id)
        )');
    }

    public function down(Schema $schema): void
    {
        // Удаляем таблицу, созданную в up
        $this->addSql('DROP TABLE IF EXISTS resources');
        
        // Воссоздаем старую таблицу
        $this->addSql('CREATE TABLE resources (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            name VARCHAR(255) NOT NULL,
            category VARCHAR(50) NOT NULL,
            drop_chance DOUBLE PRECISION NOT NULL,
            PRIMARY KEY(id)
        )');
    }
}
