monolog:
    channels: ['app']
    handlers:
        main:
            type: rotating_file
            max_files: 7
            path: '%kernel.logs_dir%/app_dev.log'
            level: debug
            channels: ['!event']
        console:
            type: console
            process_psr_3_messages: false
            channels: ['!event', '!doctrine', '!console']
        gathering:
            type: rotating_file
            path: '%kernel.logs_dir%/gathering.log'
            level: debug
            max_files: 7
            channels: ['app']
